Rails:
  Enabled: true

AllCops:
  DisplayCopNames: true

Style/IndentationWidth:
  Width: 2

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%':  '{}'
    '%i': '{}'
    '%q': '{}'
    '%Q': '{}'
    '%r': '{}'
    '%s': '{}'
    '%w': '{}'
    '%W': '{}'
    '%x': '{}'

Style/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Style/BlockDelimiters:
  EnforcedStyle: braces_for_chaining

Style/Documentation:
  Enabled: false

Style/IndentHash:
  EnforcedStyle: consistent

Style/MultilineMethodCallBraceLayout:
  EnforcedStyle: new_line

Metrics/BlockLength:
  CountComments: false
  Max: 25
  Exclude:
    - app/admin/*.rb
  ExcludeMethods:
    - context
    - describe
    - it
    - shared_examples

Metrics/LineLength:
  Max: 100
