# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 5aae216bdf59bff13abe197efc9bbc1c1a1ce945f0298f63e318708b804cb1d5e81823e681a46fd08ef3128297b0560e5735ecdb52e91bac72f81ae013f26e2c

test:
  secret_key_base: 42393956d9107baacde81ea3a971f978baa670e2dcf960e985001d00297a7c1c71b39c885096171357345fb26c2594637d04b715d5499f93d3cebd1900f90eae

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
